### ISSUE TITLE
the process killed when I run the fine grained model of MNIST database,but the cascade model works,so how does it happen?

### ISSUE THREAD

**Issue by liu9x** [kingfengji/gcForest#10]
[ 2017-07-11 18:42:43,583][fgnet.fit_transform] X_train.shape=(60000, 1, 28, 28), y_train.shape=(60000,), X_test.shape=(10000, 1, 28, 28), y_test.shape=(10000,)
[ 2017-07-11 18:42:43,584][fg_win_layer.fit_transform] [data][win1/7x7], bottoms=[u'X', u'y'], tops=[u'win1/7x7/ets', u'win1/7x7/rf']
[ 2017-07-11 18:42:43,584][fg_win_layer.fit_transform] [progress][win1/7x7] ti=0/2, top_name=win1/7x7/ets
[ 2017-07-11 18:42:43,621][fg_win_layer.fit_transform] [data][win1/7x7,train] bottoms.shape=60000x1x28x28,60000
[ 2017-07-11 18:42:43,634][win_utils.get_windows] get_windows_start: X.shape=(60000, 1, 28, 28), X_win.shape=(49, 7260000), nw=11, nh=11, c=1, win_x=7, win_y=7, stride_x=2, stride_y=2
[ 2017-07-11 18:42:44,037][win_utils.get_windows] get_windows_end
[ 2017-07-11 18:42:44,134][fg_win_layer.fit_transform] [data][win1/7x7,test] bottoms.shape=10000x1x28x28,10000
[ 2017-07-11 18:42:44,139][win_utils.get_windows] get_windows_start: X.shape=(10000, 1, 28, 28), X_win.shape=(49, 1210000), nw=11, nh=11, c=1, win_x=7, win_y=7, stride_x=2, stride_y=2
[ 2017-07-11 18:42:44,371][win_utils.get_windows] get_windows_end
[ 2017-07-11 18:42:46,279][base_estimator.fit] X_train.shape=(4839516, 49), y_train.shape=(4839516,)
已杀死

**Comment by this-Clv** [comment]
因为在进行Multi-Grained Scanning的时候，会直接创建一个非常大的矩阵，这个矩阵用来存储你MGS之后的数据，因为步进长度为1，且一帧数据有多个维度（这里只针对语音数据而言），所以这么划分下来后，数据会非常庞大，这是第一；

第二，在MGS中，还要对划分好的数据进行训练，这个过程还是Parallel的，一瞬间基本会把CPU和内存跑满，内存不够的话，在这里也是会被杀死的。

以上是我认为MGS两点很容易进程被杀死的情况，基本就是内存不够！

**Comment by kingfengji** [comment]
random forests are not so mem-friendly, 
You can try set the n_trees or max_depth to a smaller value, or change another computer with large RAM.

**Comment by this-Clv** [comment]
作者在线了:)

请教几个问题：
1. MGS当中的pool层所代表实际作用是什么？
2. 理论上来说是每个森林的树越多越好吗？我观察到sklearn官网对单个森林是这么描述的，但实际训练当中（我的数据是TIMIT），树在达到一定量的时候，准确度实际会下降，和官网描述不符。
3. 请问有试过其他的基学习器吗？我拿adaboosting（使用sklearn的默认基学习器，决策树桩，参数使用默认）的两种不同算法，SAMME和SAMME.R试了下，针对不同数据库而言，adaboosting和RF的表现不一，但数据量趋向于很大的时候，RF表现会较好，且交叉搭配过，RF和CRF的搭配是效果最好的。

斗胆中文提问了，如果要英文的话，我再翻译过来，十分感谢！

**Comment by kingfengji** [comment]
1. it is just like pooling in Conv-nets, no differences
2. No.  Increasing the number of trees per forest doesn't always help for performance, but it is quite robust..That is, changing this parameter in a reasonable range wont change the result too much.
3.  This is a deep-meta-algorithm with emphasis on the ensemble learning part. you could use anything else you like. Be creative and Have fun. :)

**Comment by this-Clv** [comment]
Thank you very much!

**Comment by kingfengji** [comment]
Please try the new APIs
