### ISSUE TITLE
I modified the model and log dir in the train_fg.py file but encountered some problems

### ISSUE THREAD

**Issue by Meow10** [kingfengji/gcForest#11]
I modified the code in the train_fg.py to test on the mnist dataset and the code is as follows:
parser.add_argument('--model', dest='models/mnist/gcforest/fg-tree500-depth100-3folds.json', type=str, required=True, help='gcfoest Net Model File')

parser.add_argument('--save_outputs', dest='save_outputs', action="store_true", help="Save outputs")

parser.add_argument('--log_dir', dest='logs/gcforest/mnist/fg', type=str, default=None, help='Log file directory')
But the program reported wrong:
usage: train_fg.py [-h] --model

MODELS/MNIST/GCFOREST/FG-TREE500-DEPTH100-3FOLDS.JSON

[--save_outputs] [--log_dir LOGS/GCFOREST/MNIST/FG]

train_fg.py: error: argument --model is required
I don't know how to solve this problem and need help. Thank you!

**Comment by this-Clv** [comment]
‘dest'  is not the location which your file locate

you can use args.dest to get the path value, like args.model, and it will return a string which is the json file's path, so you just use this 

python train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --save_outputs --log_dir your_log_dir

**Comment by kingfengji** [comment]
like @this-Clv said,
Change 
parser.add_argument('--model', dest='models/mnist/gcforest/fg-tree500-depth100-3folds.json', type=str, required=True, help='gcfoest Net Model File')
to 
parser.add_argument('--model', dest='model', default='models/mnist/gcforest/fg-tree500-depth100-3folds.json', type=str, help='gcfoest Net Model File')
