### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by nbouck** [kingfengji/gcForest#12]
So I ran the UCI letter training data with:

python tools/train_cascade.py --model models/uci_letter/gcforest/ca-tree500-n4x2-3folds.json --log_dir logs/gcforest/uci_letter/ca

After the training finished I am looking at
In [1]: object

Can I pass images of letters into gcTree for classification at this point?

Generally speaking I'm not sure what to do once training is finished...

**Comment by this-Clv** [comment]
![image](https://user-images.githubusercontent.com/11899688/29245598-27fc5462-8011-11e7-826b-b84a6d39ba78.png)

The last sentence which begin with [Result] is your finally trainning result

What do you want?

**Comment by kingfengji** [comment]
hi @nbouck sorry for the delay.
as @this-Clv said, the last line in the script is for debugging , if you dont want that,  you could please just uncomment it.
