### ISSUE TITLE
fail to install tensorflow 

### ISSUE THREAD

**Issue by sue2415535899** [kingfengji/gcForest#13]
tensorflow can be only devloped with python3.X,but other package is developed with python 2.7.how can i developed tensorflow with python 2.7? looking forward to your reply.

**Comment by kingfengji** [comment]
tensorflow can be used in 2.7 also on linux/macos platform. besides tensorflow is only used for loading data via keras. if you know how to pre-load mnist/cifar10/imdb by yourself, actually you dont need to install tf/keras at all.
