### ISSUE TITLE
How to use gcforest to fit my own dataset?

### ISSUE THREAD

**Issue by leeeeeeo** [kingfengji/gcForest#14]
In the README, it says I can refer lib/datasets/mnist.py as an example for my own dataset.
But the MNIST dataset downloaded by mnist.py is a .npz file.
And my own dataset is consisted of pictures.
So, could you please tell me more about how to use gcforest on my own dataset?
Thank you so much .

**Comment by feiyuxinfeng** [comment]
1）write your dataset.py as like mnist.py to produce the dataset
2） lib/datasets/__init__.py should be added some lines in accordance with dataset.py
3）write your own models json files in /lib/models/your_dataset

**Comment by kingfengji** [comment]
I have finished an sklearn-liked API.

I was busy on some other projects. Very soon you will be more convenient of doing so. ( currently just follow the readme and you can fit your own data.

**Comment by leeeeeeo** [comment]
@kingfengji Thank you so much ! 
Really appreciate your work !
And I'm looking forward to seeing your API !

**Comment by leeeeeeo** [comment]
@feiyuxinfeng Thank you for your guidance !
I'll try according to your steps .
Again , thank you so much !

**Comment by eokahn** [comment]
@kingfengji looking forward to the API!
