### ISSUE TITLE
Does gcforest can only run on cpu?

### ISSUE THREAD

**Issue by leeeeeeo** [kingfengji/gcForest#15]
When I run demos, it seems that the program doesn't use gpu .
And I saw the program outputs "Using TensorFlow backend."
But , I didn't find a "import tensorflow" in codes.
So, is there anything wrong with my understanding  OR  it can't use gpu  OR  how to use gpu?
Thank you so much !

**Comment by feiyuxinfeng** [comment]
Keras uses TensorFolw backend
This version doesn't support GPU

**Comment by feiyuxinfeng** [comment]
Keras uses TensorFolw backend
This version doesn't support GPU

**Comment by kingfengji** [comment]
actually it can be run on CPU.
keras is only used for loading mnist data. you can un-comment it if you have one.
so NO need GPU at all.

**Comment by leeeeeeo** [comment]
@kingfengji @feiyuxinfeng Thank you both soooooooooo much !
