### ISSUE TITLE
I intend to run MNIST,after a corresponding change according to README.md,but some problem have arisen

### ISSUE THREAD

**Issue by zhaopanpan73** [kingfengji/gcForest#16]
root@ballonflower-HP-Pavilion-Notebook:/home/ballonflower/gcForest-master# python tools/train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --log_dir logs/gcforest/mnist/fg --save_outputs
Using TensorFlow backend.
[ 2017-09-07 16:19:28,970][train_fg.<module>] tools.train_fg
[ 2017-09-07 16:19:28,971][train_fg.<module>] 
{
    "dataset":{
        "test":{
            "data_set":"test",
            "layout_x":"tensor",
            "type":"mnist"
        },
        "train":{
            "data_set":"train",
            "layout_x":"tensor",
            "type":"mnist"
        }
    },
    "net":{
        "layers":[
            {
                "bottoms":[
                    "X",
                    "y"
                ],
                "estimators":[
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"ExtraTreesClassifier"
                    },
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"RandomForestClassifier"
                    }
                ],
                "n_classes":10,
                "name":"win1/7x7",
                "stride_x":2,
                "stride_y":2,
                "tops":[
                    "win1/7x7/ets",
                    "win1/7x7/rf"
                ],
                "type":"FGWinLayer",
                "win_x":7,
                "win_y":7
            },
            {
                "bottoms":[
                    "X",
                    "y"
                ],
                "estimators":[
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"ExtraTreesClassifier"
                    },
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"RandomForestClassifier"
                    }
                ],
                "n_classes":10,
                "name":"win1/10x10",
                "stride_x":2,
                "stride_y":2,
                "tops":[
                    "win1/10x10/ets",
                    "win1/10x10/rf"
                ],
                "type":"FGWinLayer",
                "win_x":10,
                "win_y":10
            },
            {
                "bottoms":[
                    "X",
                    "y"
                ],
                "estimators":[
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"ExtraTreesClassifier"
                    },
                    {
                        "max_depth":100,
                        "min_samples_leaf":10,
                        "n_estimators":500,
                        "n_folds":3,
                        "n_jobs":-1,
                        "type":"RandomForestClassifier"
                    }
                ],
                "n_classes":10,
                "name":"win1/13x13",
                "stride_x":2,
                "stride_y":2,
                "tops":[
                    "win1/13x13/ets",
                    "win1/13x13/rf"
                ],
                "type":"FGWinLayer",
                "win_x":13,
                "win_y":13
            },
            {
                "bottoms":[
                    "win1/7x7/ets",
                    "win1/7x7/rf",
                    "win1/10x10/ets",
                    "win1/10x10/rf",
                    "win1/13x13/ets",
                    "win1/13x13/rf"
                ],
                "name":"pool1",
                "pool_method":"avg",
                "tops":[
                    "pool1/7x7/ets",
                    "pool1/7x7/rf",
                    "pool1/10x10/ets",
                    "pool1/10x10/rf",
                    "pool1/13x13/ets",
                    "pool1/13x13/rf"
                ],
                "type":"FGPoolLayer",
                "win_x":2,
                "win_y":2
            }
        ],
        "outputs":[
            "pool1/7x7/ets",
            "pool1/7x7/rf",
            "pool1/10x10/ets",
            "pool1/10x10/rf",
            "pool1/13x13/ets",
            "pool1/13x13/rf"
        ]
    },
    "train":{
        "data_cache":{
            "cache_dir":"/mnt/raid/fengji/gcforest/mnist/fg-tree500-depth100-3folds/datas",
            "cache_in_disk":{
                "default":1
            },
            "keep_in_mem":{
                "default":0
            }
        },
        "keep_model_in_mem":0,
        "random_state":0
    }
}
Traceback (most recent call last):
  File "tools/train_fg.py", line 45, in <module>
    data_train = get_dataset(config["dataset"]["train"])
  File "lib/gcforest/datasets/__init__.py", line 52, in get_dataset
    return ds_class(**ds_config)
  File "lib/gcforest/datasets/mnist.py", line 24, in __init__
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
  File "/usr/local/lib/python2.7/dist-packages/keras/datasets/mnist.py", line 16, in load_data
    f = np.load(path)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 412, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 171, in __init__
    _zip = zipfile_factory(fid)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 101, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
Exception AttributeError: "'NpzFile' object has no attribute 'zip'" in <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x7fa6a707ef10>> ignored

**Comment by zhaopanpan73** [comment]
The problem has solved.Thanks a lot

**Comment by feiyuxinfeng** [comment]
cache_dir hasn't been changed.

**Comment by zhaopanpan73** [comment]
the process killed when I run the fine grained model of MNIST database,  and my single node configuration is: the blade calculation node adopts two Intel Xeon e5-2692v2, 12 core processor (2.60 GHz),A total of 24 core computing 1.8Tsas hard disk, and 64GB memory is configured.
Can the you talk about the specific  environment configuration in your experiment? Expectiong for your reply

**Comment by kingfengji** [comment]
64 G should serve you well. make sure no other program is running at the same time. thanks. and again @feiyuxinfeng  is right.
