### ISSUE TITLE
signal data training

### ISSUE THREAD

**Issue by JenniferCreep** [kingfengji/gcForest#18]
Hi, 
Currently, I am trying to use this model for the EEG signal training, the data is 1-d, not 2-d( not image).

Then, according to the DataFormat requirement: Data Format-------"
0. Please refer lib/datasets/mnist.py as an example the dataset should has attribute X,y to represent the data and label y should be 1-d array
For fine-grained scanning, X should be 4-d array (N x channel x H x W). (e.g. cifar10 shoud be Nx3x32x32, mnist should be Nx1x28x28, uci_semg should be Nx1x3000x1)."--------

Kind of confused about it, could you help me about how to change the code to meet my own dataset training?
Great thanks.

**Comment by kingfengji** [comment]
please take a look at the new readme.md at the homepage for this project thanks
