### ISSUE TITLE
Issue about the demo MNIST

### ISSUE THREAD

**Issue by leeeeeeo** [kingfengji/gcForest#19]
@kingfengji 
Hi!
    I'm trying to run the demo following the readme.txt.
    When I tried to train the MNIST, I input this :
![image](https://user-images.githubusercontent.com/25877709/31849902-c5bf47b2-b67c-11e7-8cc8-12d022777b04.png)
    And the program begins running.
    BUT, it stopped here:
![image](https://user-images.githubusercontent.com/25877709/31849908-ee0c0c14-b67c-11e7-84d4-c29c0d6ff1d8.png)
    I've been waiting for a long time, but it just stopped, no error or warning.
    What happened to the demo? Did I do something wrong?
    Looking forward to your reply.
    Thank you.

**Comment by RayShark** [comment]
I also have that problem, did you slove that?
Maybe it's because our computers RAM is too low?

**Comment by leeeeeeo** [comment]
@RayShark Actually it's because my poor computer .
I tried it on a 128G RAM computer, and waited for a long time, finally it began running.
The whole program ran about 12 hours.   : )
But I still don't know how to use the result of the training.   : (

**Comment by RayShark** [comment]
@leeeeeeo Well, I'm afraid that my computer can't run it at all.
I will try it on the server later, it is quite a hard task.
Thanks a lot~

**Comment by kingfengji** [comment]
try the new api
