### ISSUE TITLE
How can I install the package?

### ISSUE THREAD

**Issue by yychenca** [kingfengji/gcForest#2]
I've been waiting for the "official package" for a long while since the original paper was released. Nice job!!

Just trying to get my head around the installation as I couldn't seem to find where to get started. It's mentioned in the readme.md that in order to make it work one needs to install the dependencies but how about the main package? My apologies if the questions sound naive but if you can add a setup.py or so that would be very helpful.

**Comment by kingfengji** [comment]
You don't need to install anything "main". 
Just goto the folder and run the script. Python will import the module for you, as indicated in the demo scripts
