### ISSUE TITLE
fg-tree500-depth100-3folds.json

### ISSUE THREAD

**Issue by zhaopanpan73** [kingfengji/gcForest#22]
"train":{
    "keep_model_in_mem":0,    
    //"model_cache_dir":"/mnt/raid/fengji/gcforest/mnist/fg-tree500-depth100-3folds/models",
    "random_state":0,
    "data_cache":{
        "cache_in_disk":{
            "default":1
        },
        "keep_in_mem":{
            "default":0
        },
        "cache_dir":"/mnt/raid/fengji/gcforest/mnist/fg-tree500-depth100-3folds/datas"
    }
}

我想问一下，上面的"keep_model_in_mem":0,  是指把训练的模型保存在外存中，如果"keep_model_in_mem":1,是把训练模型保存在内存中，但是，我不知道 "data_cache"和 "cache_dir"是什么含义，是用来保存什么的。能帮忙解答一下吗

**Comment by kingfengji** [comment]
I have updated a more user-friendly api, please check the new one
