### ISSUE TITLE
gc训练的模型测试结果固定100个是为什么?

### ISSUE THREAD

**Issue by leeeeeeo** [kingfengji/gcForest#28]
您好!
我用demo_mnist-gc.json训练了一个模型.
测试的时候,出现如下图所示的情况.
测试时,我输入788张32x32的RGB彩色图像,但是最后y_pred只输出了100个值是为什么?不应该输出788个值吗?
希望收到您的回复!谢谢!
![screenshot from 2018-01-29 18 19 23](https://user-images.githubusercontent.com/25877709/35505617-9839e088-0521-11e8-96c2-77139dad8fc2.png)

**Comment by leeeeeeo** [comment]
补一张图,训练的时候也是一样,前面训练层的时候还是好好地,后面就全变成100个了.是为啥?
![screenshot from 2018-01-29 19 52 35](https://user-images.githubusercontent.com/25877709/35509194-337d0348-052e-11e8-857a-5724c06be00d.png)

**Comment by leeeeeeo** [comment]
@kingfengji 忘记艾特了...希望收到您的回复!

**Comment by kingfengji** [comment]
@leeeeeeo I've updated the code, try it now. The second time you use the model, it should return the new results.
It should be all right now.
Thanks.
