### ISSUE TITLE
Maybe,there is something wrong in "gcforest-master/lib/gcforest/cascade/cascade_classifier.py"?

### ISSUE THREAD

**Issue by zhaopanpan73** [kingfengji/gcForest#29]
in the function "def _check_group_dims (self, X_groups, is_fit):"    

   if is_fit:
                group_dims.append( X_group.shape[1] )
               #According to the paper. I think the  next line code should be
               # " group_starts.append(i if i == 0 else group_starts[i - 1] + group_dims[i-1])"
                group_starts.append(i if i == 0 else group_starts[i - 1] + group_dims[i])
                group_ends.append(group_starts[i] + group_dims[i])

     because the look _indexs_cycle are[[0,1],[2,3],[4,5]] those are consecutive.so the original input ( six pool1) should next to each other.if write like this  "group_starts.append(i if i == 0 else group_starts[i - 1] + group_dims[i])"  ,one of the look_index_cycle which is input to the layer is not consecutive.
    Is that right? I am thinking

**Comment by kingfengji** [comment]
@zhaopanpan73 you are right. This is a bug when I writing a cleaned version for public useage.
The good news is that the perforance hasn't been changed much (e.g. MNIST 99.30 to 99.25%)
I have updated the code. 
Thank you for the feed back.
