### ISSUE TITLE
Cascade gcForest not working due to missing xrange() function in Python 3.5

### ISSUE THREAD

**Issue by slazien** [kingfengji/gcForest#31]
I am trying to run a minimal example of a cascade classifier. However, it fails due to the xrange() function not being implemented in Python 3.5.The example goes as follows (omitting config and definition of training data for clarity):

`from gcforest.gcforest import GCForest`
`gc = GCForest(config)`
`gc.fit_transform(X_train, y_train, X_test, y_test)`

**Comment by elliotdawson** [comment]
I had the same issue until I just modified cascade_classifier to use 'range' instead of 'xrange'. I think this is a Python 3 vs Python 2.7 issue.

**Comment by kingfengji** [comment]
@slazien @elliotdawson 
Thanks for your feedback. I have fixed this problem.
