### ISSUE TITLE
Could you tell me which conference was this essay published?  I want to download this paper,hoping your help

### ISSUE THREAD

**Issue by jfgg95** [kingfengji/gcForest#33]

**Comment by ekamioka** [comment]
I am not sure if I got the question correctly, but maybe this link can help you: http://lamda.nju.edu.cn/code_gcForest.ashx

**Comment by kingfengji** [comment]
@ekamioka thanks,
@jfgg95 
Z.-H. Zhou and J. Feng. Deep forest: Towards an alternative to deep neural networks. In: Proceedings of the 26th International Joint Conference on Artificial Intelligence (IJCAI'17), Melbourne, Australia, 2017, pp.3553-3559.
