### ISSUE TITLE
ImportError: No module named gcforest.gcforest

### ISSUE THREAD

**Issue by zhoumingyi** [kingfengji/gcForest#36]
I don't know how to fix it. I run `pip install -r requirements.txt` successfully. But it alerts me another error:

`Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/mingyi/gcForest-master/examples/demo_mnist.py", line 19, in <module>
    from gcforest.gcforest import GCForest
ImportError: No module named gcforest.gcforest`
Thanks!

**Comment by zhoumingyi** [comment]
I have fixed it. Modify the sys.path, then this code run successfully

**Comment by mistaken2** [comment]
Hello, you must copy the lib/gcforest directory to to the python install directory, as shwos:
