### ISSUE TITLE
ValueError: look_indexs unlegal!!! look_indexs=[6, 7]

### ISSUE THREAD

**Issue by dandanli814** [kingfengji/gcForest#5]
When I am trying to run "python tools/train_cascade.py --model models/mnist/gcforest/fg-tree500-depth100-3folds-ca.json", there is an error as the fllowing:

File "lib/gcforest/cascade/cascade_classifier.py", line 123, in fit_transform
    raise ValueError("look_indexs unlegal!!! look_indexs={}".format(look_indexs))
ValueError: look_indexs unlegal!!! look_indexs=[6, 7]

I don't know what's the problem, can anyone help me?

**Comment by kingfengji** [comment]
Uncomment this line. 

It means cyclic cascading the input. Check the latest version of paper. Thanks.

**Comment by dandanli814** [comment]
OK, I have solved this problem.Thank you.
And I will read the latest.

**Comment by kingfengji** [comment]
great, thank.
I'll make an update(delete this line) on the model for this issue.

**Comment by dandanli814** [comment]
OK, thank you, that's will be great.
