### ISSUE TITLE
cannot find the '*.pkl' datas

### ISSUE THREAD

**Issue by kkhuang1990** [kingfengji/gcForest#6]
an error came out when I ran 'python tools/train_cascade.py --model models/mnist/gcforest/fg-tree500-depth100-3folds-ca.json' after running `python tools/train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --log_dir logs/gcforest/mnist/fg --save_outputs`: 

`Loading data from /data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree300-depth0/datas/train/outputs.pkl
Traceback (most recent call last):
  File "tools/train_cascade.py", line 38, in <module>
    data_train = get_dataset(config["dataset"]["train"])
  File "lib/gcforest/datasets/__init__.py", line 52, in get_dataset
    return ds_class(**ds_config)
  File "lib/gcforest/datasets/ds_pickle2.py", line 17, in __init__
    with open(data_path) as f:
IOError: [Errno 2] No such file or directory: u'/data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree300-depth0/datas/train/outputs.pkl'`

I thought the 'outputs.pkl' file should be generated after running train_cascade.py but not before running i; however, I may be wrong. Is there some setting for the path where the outputs.pkl is saved. 

Best regards!

**Comment by kkhuang1990** [comment]
thanks for your reply.
actually I carefully checked the setting in lib/gcforest/fgnet.py for the output file, which is as follows:
```
if save_path is None:
            if self.data_cache.cache_dir is None:
                LOGGER.error("save path is None and data_cache.cache_dir is None!!! don't know where to save")
                return
            save_path = osp.join(self.data_cache.cache_dir, phase, "outputs.pkl")
```
However, my output is saved as '.npz' format. For the same output path `/data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree500-depth100-3folds/datas`, two folders 'train' and 'test' are created, within which 'win1-7x7-ets.npy' and  'win1-7x7-rf.npy' are saved. Could you tell me  where the setting of '.npz' output format is made as I cannot find the specific file for this setting

Best regards!

**Comment by dandanli814** [comment]
@kkhuang1990  I think the setting is in "/gcForest/lib/gcforest/data_cache.py" line 25, but I am not sure, you can try it.

**Comment by this-Clv** [comment]
Did you run the train_fg.py first? 

The train_cascade.py is the second step , you need run train_fg.py to generate the pkl data, then train_cascade.py will work.

Also ,you can run train_cascade.py without the first step by using another json file ‘ca-tree500-n4x2-3folds.json’.

And all of this usage are presented in the README.txt.
![image](https://user-images.githubusercontent.com/11899688/29245706-9492ab86-8015-11e7-9cd5-012e6c7960c3.png)

**Comment by kingfengji** [comment]
the npz file is not the same thing as outputs.pkl.
if you defined data_save_dir=“/data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree500-depth100-3folds” 
in 
models/mnist/gcforest/fg-tree500-depth100-3folds-ca.json. 

After you run 
`python tools/train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --log_dir logs/gcforest/mnist/fg --save_outputs`

it should be saved in 
/data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree500-depth100-3folds/train/outputs.pkl 
and 
/data/unagi0/CT_Anomaly_Detection/Huang/gcforest/cache/mnist/fg-tree500-depth100-3folds/test/outputs.pkl 

Notice, make sure you have set the same data_save_dir in you finegrained and cascade config file and you have passed the  (—save_cache) option when running python tools/train_fg.py
