### ISSUE TITLE
gpu acceleration doesn't work for xgboost-only structure

### ISSUE THREAD

**Issue by ZhouY-JustLL** [kingfengji/gcForest#67]
I used only xgboost classifier for cascade forest, and used gpu for training by setting`"gpu_id": 0, tree_method: "gpu_hist"`. When the training was started, I checked the memory usage of gpu and it showed that the python script is using gpu. 
    But when I compared the gpu method with the cpu method, the time consuming had no significant change, results are almost the same.
    The xgboost version is 0.82. Nvidia 1080Ti gpu.

**Comment by tutu96177** [comment]
Hi kingfeng,
     I hope we can comunicate by wechat. My wechat is chshichao。







At 2019-05-16 18:16:56, "ZhouY-JustLL" <notifications@github.com> wrote:

I used only xgboost classifier for cascade forest, and used gpu for training by setting`"gpu_id": 0, tree_method: "gpu_hist"`. When the training was started, I checked the memory usage of gpu and it showed that the python script is using gpu. 
But when I compared the gpu method with the cpu method, the time consuming had no significant change, results are almost the same.
The xgboost version is 0.82. Nvidia 1080Ti gpu.
