### ISSUE TITLE
Hi, How could  I reuse the model after training?

### ISSUE THREAD

**Issue by zhanghewan** [kingfengji/gcForest#7]
that is to say how to save the trained whole model to disk, in order to reuse the model with other test set to evaluate the performance. Because  each time to evaluate test set need to retrain the model, which waste too much time. 
 Thank you.

**Comment by kingfengji** [comment]
In later development, saving model api will be supported. however, you might be interested in the " cache " way of doing things, as mentioned in [issue 8](https://github.com/kingfengji/gcForest/issues/8)

**Comment by kingfengji** [comment]
now you can save it to disk.
