### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'n_classes_'

### ISSUE THREAD

**Issue by Jack-Chow-my** [kingfengji/gcForest#8]
There was an error when I ran 'python tools/train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --log_dir logs/gcforest/mnist/fg --save_outputs'

Traceback (most recent call last):
  File "tools/train_fg.py", line 49, in <module>
    net.fit_transform(data_train.X, data_train.y, data_test.X, data_test.y, train_config)
  File "lib/gcforest/fgnet.py", line 53, in fit_transform
    layer.fit_transform(train_config)
  File "lib/gcforest/layers/fg_win_layer.py", line 106, in fit_transform
    keep_model_in_mem=train_config.keep_model_in_mem)
  File "lib/gcforest/estimators/kfold_wrapper.py", line 103, in fit_transform
    y_proba = est.predict_proba(X[val_idx].reshape((-1, n_dims)), cache_dir=cache_dir)
  File "lib/gcforest/estimators/base_estimator.py", line 80, in predict_proba
    batch_size = batch_size or self._default_predict_batch_size(est, X)
  File "lib/gcforest/estimators/sklearn_estimators.py", line 44, in _default_predict_batch_size
    return forest_predict_batch_size(clf, X)
  File "lib/gcforest/estimators/sklearn_estimators.py", line 23, in forest_predict_batch_size
    mem_size_1 = clf.n_classes_ * clf.n_estimators * 16
AttributeError: 'NoneType' object has no attribute 'n_classes_'

I tired to debug the code, but I could not solve the problems. I will appreciate it if anyone can help me.
Thanks a lot!

**Comment by nbouck** [comment]
I had a similar error:
AttributeError: type object 'NewBase' has no attribute 'is_abstract'
This fixed my issue:
sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"
Shouldn't TF test for a particular six version, or at least help the user on his way.

**Comment by Jack-Chow-my** [comment]
Thank you very much for your detailed reply!
I checked the six version, which is actually 1.10.
I think the version of some package is wrong, but I don't know which one is wrong.

**Comment by kingfengji** [comment]
@Jack-Chow-my 
Did you run the code and canceled it half-way?
gcforest will cache the result for fit/predictions, the propose here is  that when next time you add a layer you don’t have to re-run the previous layers. Very accidentally you may cancelled the program when the fit phase is done while the predicting phase is not. This may lead to errors.

So the next you run the code, gcforest will try to load the prediction result from cache and skip create the real estimator.

You can try delete the cache directory (which defined by the data_save_dir param in models/mnist/gcforest/fg-tree500-depth100-3folds.json) and rerun the code.

**Comment by Jack-Chow-my** [comment]
Thank you very much for your detailed reply!

**Comment by ssdyue** [comment]
@Jack-Chow-my  have you solved the problem？i have tried this solution, but it didn't work.

**Comment by Jack-Chow-my** [comment]
@ssdyue  sorry for the delay. I deleted all the results generated before, and rerun  again, the problem was solved. Or even you can unzip the file, and try to do it from the beginning. Hope it will help.
